## Numpy array and basics

In [1]:
import numpy as np 


# Creating Array from list

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5]) # Creating a 1D NumPy array with list because array takes  a list as input
print("1D Array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]]) # Creating a 2D NumPy array with list of lists
print("2D Array:\n", arr_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


### List vs Numpy Array

In [3]:
py_list = [1,2,3]
print("Python list multpilication: " , py_list * 2) # it will do list repetition, not element-wise multiplication

np_array = np.array([1,2,3])
print("NumPy array multiplication: ", np_array * 2) # it will do element-wise multiplication


import time

start = time.time()
list1 = [i*2 for i in range(1000)]
print("Time taken for list element multiplicaation:", time.time() - start)

start = time.time()
arr1 = np.arange(1000) * 2
print("Time taken for NumPy array operation:", time.time() - start)


Python list multpilication:  [1, 2, 3, 1, 2, 3]
NumPy array multiplication:  [2 4 6]
Time taken for list element multiplicaation: 0.0
Time taken for NumPy array operation: 0.0010051727294921875


### Creating Array From Scratch

In [13]:
zeros = np.zeros((3,4)) # 3 rows and 4 columns
print(f"zeros array:\n {zeros}")

ones = np.ones((3,4)) # 3 rows and 4 columns
print(f"Ones array: \n {ones}")

full = np.full((2,2) , 5)
print(f"full array with 5: \n{full}")

random = np.random.random((2,2)) # 2 rows and 2 columns
print(f"Random array: \n{random}")

sequence = np.arange(0, 10 , 2) # start from 0 end at 10 with step 2
print(f"sequence array: \n{sequence}")

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array with 5: 
[[5 5]
 [5 5]]
Random array: 
[[0.07430818 0.91154987]
 [0.22410519 0.11253134]]
sequence array: 
[0 2 4 6 8]


### Vector, Matrix and Tensor

In [ ]:
vector = np.array([1, 2, 3])
print(f"Vector: {vector}")

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Matrix:\n{matrix}")

tensor = np.array([[[1,2] , [3,4]] , 
                   [[5,6] , [7,8]]]) 
print(f"Tensor:\n{tensor}")

Vector: [1 2 3]
Matrix:
[[1 2 3]
 [4 5 6]]
Tensor:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Propertities

In [22]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.int64)  # Specifying data type as int64
print(f"Array shape: {arr.shape}")  # Output: (5,)
print(f"dimensions: {arr.ndim}")  # Output: 1
print(f"size: {arr.size}")  # Output: 5
print(f"data type: {arr.dtype}")  # Output: int64 (or int32 depending on the system)

print("\n")
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Array shape: {arr.shape}")  # Output: (2, 3)    
print(f"dimensions: {arr.ndim}")  # Output: 2
print(f"size: {arr.size}")  # Output: 6
print(f"data type: {arr.dtype}")  # Output: int64 (or int32 depending on the system)


Array shape: (5,)
dimensions: 1
size: 5
data type: int64


Array shape: (2, 3)
dimensions: 2
size: 6
data type: int32


### Array Reshaping

In [ ]:
arr = np.arange(12)
print(f"Original array: {arr}")

reshaped = arr.reshape(3, 4)  # Reshape to 3 rows and 4 columns
print(f"Reshaped array:\n{reshaped}")

flattened = reshaped.flatten()  # Flatten the array back to 1D
print(f"Flattened array: {flattened}")

ravel = reshaped.ravel()  # Ravel the array (similar to flatten but returns a view if possible)
print(f"Ravelled array: {ravel}")


Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravelled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Modified flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


### Transpose

In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

transposed = arr.T # Transpose the array or use np.transpose(arr)
print(transposed)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### List vs Numpy Array