## Numpy Array Operations

In [1]:
import numpy as np

### Indexing and slicing

In [26]:
# Basic Slicing in NumPy with 1D array
arr = np.array([1, 2, 3, 4, 5 , 6 ,7 , 8 , 9 , 10])
print(f"Basic Slicing: \n{arr[2:5]}") # start from 2 and end at 5 (exclusive)
print(f"Basic Slicing with step: \n{arr[2:8:2]}") # start from 2, end at 8 (exclusive) with step of 2


# Basic Slicing in NumPy with 2D array
arr2d = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12]
])

print(f"At row 1 and column 2 => element is: {arr2d[1][2]}")
print(f"Entire row: {arr2d[1]}") # prints entire row 1
print(f"Entire column: {arr2d[:, 2]}") # prints entire column 2





Basic Slicing: 
[3 4 5]
Basic Slicing with step: 
[3 5 7]
At row 1 and column 2 => element is: 7
Entire row: [5 6 7 8]
Entire column: [ 3  7 11]


### Sorting

In [36]:
arr = np.array([4,5,2,9,0,2,1])

sorted = np.sort(arr)
print(f"Original array: {arr}")
print(f"Sorted array: {sorted}")

#sorted 2d array
arr2d = np.array([
    [7, 2, 9],
    [4, 5, 6],
    [3, 8, 1]
])

print(f"Original 2D array:\n{arr2d}")

sorted = np.sort(arr2d , axis=0) # sort along the first axis (columns)
print(f"Sorted 2D array along first axis:\n{sorted}")

sorted = np.sort(arr2d , axis=1) # sort along the second axis (rows)
print(f"Sorted 2D array along second axis:\n{sorted}")

Original array: [4 5 2 9 0 2 1]
Sorted array: [0 1 2 2 4 5 9]
Original 2D array:
[[7 2 9]
 [4 5 6]
 [3 8 1]]
Sorted 2D array along first axis:
[[3 2 1]
 [4 5 6]
 [7 8 9]]
Sorted 2D array along second axis:
[[2 7 9]
 [4 5 6]
 [1 3 8]]


## Filtering

In [38]:
numbers = np.array([1, 2, 3, 4, 5,6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print(f"Even numbers: {even_numbers}")

odd_numbers = numbers[numbers % 2 != 0]
print(f"Odd numbers: {odd_numbers}")

Even numbers: [ 2  4  6  8 10]
Odd numbers: [1 3 5 7 9]


## Filter with Mask

In [40]:
numbers = np.array([1, 2, 3, 4, 5 , 6 ,7 , 8 , 9 , 10])
mask = numbers > 5

print(f"Original array: {numbers}")
print(f"Mask (numbers > 5): {numbers[mask]}")


Original array: [ 1  2  3  4  5  6  7  8  9 10]
Mask (numbers > 5): [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [ ]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

indices = [0 , 2, 5]

print(f"Numbers: {numbers[indices]}")

where_result = np.where(numbers > 5)
print(f"Indices where numbers > 5: {numbers[where_result]}")

                          #Condition   value if true   value if false
condition_array = np.where(numbers > 5 , numbers * 6 , numbers )
print(f"Condition array (numbers > 5 ? numbers * 2 : numbers): {condition_array}")

Numbers: [1 3 6]
Indices where numbers > 5: [ 6  7  8  9 10]
Condition array (numbers > 5 ? numbers * 2 : numbers): [ 3  6  9 12 15 36 42 48 54 60]


## Adding and removing data

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])


3
